#version: '3.9'
services:
  db:
    container_name: db_tour
    image: mariadb:10.11.6
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root_DB_tuor"
      MYSQL_DATABASE: "db_tour"
      MYSQL_USER: "user_tour"
      MYSQL_PASSWORD: "pass_tour"
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    #restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
  backennd:
    # image: node
    container_name: backend-nodejs-tour
    build: ./backend
    volumes:
      - './backend/index.js:/app/index.js'
      - '/app/node_modules'
    ports:
      - "8080:8080"
    depends_on:
      - db
  frontend:
    container_name: frontend-reactjs-tour
    build: ./frontend
    volumes:
      - './frontend:/usr/src/app:delegated'
      - '/app/node_modules'
    tty: true
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
      - backennd
    stdin_open: true

#frontend
#npm init
#npx create-react-app [projectname] || npm install -g create-react-app

#backend
#npm init
#npm i express cors dotenv